class MissionConstants:
    class MissionType:
        RESOURCE_COLLECTION = "RESOURCE_COLLECTION"
        RESEARCH = "RESEARCH"
        BUILD_WORKER = "BUILD_WORKER"
        BUILD_CITY_TILE = "BUILD_CITY_TILE"
        EXPLORATION = "EXPLORATION"
        CLUSTER_GUARD = "CLUSTER_GUARD"
